Grammar

    0 $accept: PROGRAM $end

    1 PROGRAM: TOP_STATEMENTS

    2 TOP_STATEMENTS: STATEMENT_VAR_DEF TOP_STATEMENTS
    3               | STATEMENT_FUNC_DEF TOP_STATEMENTS
    4               | STATEMENT_STRUCT_DEF TOP_STATEMENTS
    5               | %empty

    6 STATEMENTS_BLOCK: BEGIN STATEMENTS END
    7                 | BEGIN END

    8 STATEMENTS: STATEMENT STATEMENTS
    9           | STATEMENT

   10 STATEMENT: STATEMENT_VAR_DEF
   11          | STATEMENT_ASSIGN
   12          | STATEMENT_IF
   13          | STATEMENT_WHILE
   14          | STATEMENT_STRUCT_DEF
   15          | STATEMENT_RETURN
   16          | STATEMENT_EXP_R
   17          | SEMICOLON

   18 EXP_R: EXP_R LT EXP_R
   19      | EXP_R LE EXP_R
   20      | EXP_R GT EXP_R
   21      | EXP_R GE EXP_R
   22      | EXP_R NE EXP_R
   23      | EXP_R EQ EXP_R
   24      | EXP_R PLUS EXP_R
   25      | EXP_R MINUS EXP_R
   26      | EXP_R STAR EXP_R
   27      | EXP_R DIVIDE EXP_R
   28      | EXP_R MOD EXP_R
   29      | EXP_R LOR EXP_R
   30      | EXP_R LAND EXP_R
   31      | LNOT EXP_R
   32      | EXP_R BOR EXP_R
   33      | EXP_R BXOR EXP_R
   34      | EXP_R APSAND EXP_R
   35      | PLUS EXP_R
   36      | MINUS EXP_R
   37      | ROUND_LEFT EXP_R ROUND_RIGHT
   38      | EXP_L
   39      | APSAND EXP_L
   40      | STAR EXP_L
   41      | NUMBER
   42      | FUNC_CALL

   43 EXP_L: ID
   44      | EXP_L DOT ID
   45      | HD_ARRAY
   46      | EXP_L DOT HD_ARRAY

   47 HD_ARRAY: ID SQUARE_LEFT EXP_R SQUARE_RIGHT
   48         | HD_ARRAY SQUARE_LEFT EXP_R SQUARE_RIGHT

   49 STATEMENT_EXP_R: EXP_R SEMICOLON

   50 NUMBER: CONST_INTEGER
   51       | CONST_BOOLEAN
   52       | CONST_FLOAT

   53 STATEMENT_IF: IF ROUND_LEFT EXP_R ROUND_RIGHT STATEMENTS_BLOCK STATEMENT_ELSE

   54 STATEMENT_ELSE: ELSE STATEMENTS_BLOCK
   55               | ELSE STATEMENT_IF
   56               | %empty

   57 STATEMENT_WHILE: WHILE ROUND_LEFT EXP_R ROUND_RIGHT WHILE_BODY

   58 WHILE_BODY: STATEMENTS_BLOCK
   59           | STATEMENT

   60 STATEMENT_VAR_DEF: VAR_DEF_TYPE DECLARE_INITIALIZE DECLARE_MORE
   61                  | VAR_DEF_TYPE DECLARE_NON_INITIALIZE DECLARE_MORE

   62 DECLARE_MORE: SEMICOLON
   63             | COMMA DECLARE_INITIALIZE DECLARE_MORE
   64             | COMMA DECLARE_NON_INITIALIZE DECLARE_MORE

   65 DECLARE_NON_INITIALIZE: ID
   66                       | STAR ID
   67                       | HD_ARRAY
   68                       | STAR HD_ARRAY

   69 DECLARE_INITIALIZE: ID ASSIGN EXP_R
   70                   | STAR ID ASSIGN EXP_R

   71 STATEMENT_ASSIGN: EXP_L ASSIGN EXP_R SEMICOLON

   72 STATEMENT_STRUCT_DEF: STRUCT ID BEGIN STRUCT_MEMBER_DEF MORE_STRUCT_MEMBER_DEF END SEMICOLON

   73 MORE_STRUCT_MEMBER_DEF: STRUCT_MEMBER_DEF MORE_STRUCT_MEMBER_DEF
   74                       | %empty

   75 STRUCT_MEMBER_DEF: VAR_DEF_TYPE DECLARE_NON_INITIALIZE DECLARE_MORE_NON_INITIALIZE SEMICOLON

   76 DECLARE_MORE_NON_INITIALIZE: COMMA DECLARE_NON_INITIALIZE DECLARE_MORE_NON_INITIALIZE
   77                            | %empty

   78 STATEMENT_RETURN: RETURN EXP_R SEMICOLON

   79 FUNC_CALL: ID ROUND_LEFT EXP_R SEND_FUNC_ARGS ROUND_RIGHT
   80          | ID ROUND_LEFT ROUND_RIGHT

   81 SEND_FUNC_ARGS: COMMA EXP_R SEND_FUNC_ARGS
   82               | %empty

   83 STATEMENT_FUNC_DEF: FUNCTION FUNC_DEF_TYPE ID ROUND_LEFT ROUND_RIGHT STATEMENTS_BLOCK
   84                   | FUNCTION FUNC_DEF_TYPE ID ROUND_LEFT SINGLE_RECV_FUNC_ARG RECV_FUNC_ARGS ROUND_RIGHT STATEMENTS_BLOCK

   85 RECV_FUNC_ARGS: COMMA SINGLE_RECV_FUNC_ARG RECV_FUNC_ARGS
   86               | %empty

   87 SINGLE_RECV_FUNC_ARG: FUNC_DEF_TYPE ID
   88                     | FUNC_DEF_TYPE RECV_HD_ARRAY

   89 RECV_HD_ARRAY: ID SQUARE_LEFT SQUARE_RIGHT PLACEHOLDER
   90              | ID SQUARE_LEFT EXP_R SQUARE_RIGHT PLACEHOLDER

   91 DT_STRUCT: STRUCT ID

   92 DT_POINTER: VAR_DEF_TYPE STAR

   93 VAR_DEF_TYPE: DT_INTEGER
   94             | DT_FLOAT
   95             | DT_BOOLEAN
   96             | DT_STRUCT

   97 FUNC_DEF_TYPE: DT_INTEGER
   98              | DT_FLOAT
   99              | DT_BOOLEAN
  100              | DT_POINTER